/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Laporan;

import Koneksi.KoneksiD;
import java.awt.event.ActionEvent;
import java.util.Date;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author mmuzaki.a
 */
public class FormLaporan extends javax.swing.JPanel {

    /**
     * Creates new form FormLaporan
     */
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormLaporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelLaporan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        PanelLaporan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAPORAN");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Laporan", "Data Barang", "Data Merek", "Data Jenis", "Data Supplier", "Data User", "Data Barang Masuk", "Data Barang Keluar" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Pilih Laporan");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print.png"))); // NOI18N
        jButton1.setText("CETAK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLaporanLayout = new javax.swing.GroupLayout(PanelLaporan);
        PanelLaporan.setLayout(PanelLaporanLayout);
        PanelLaporanLayout.setHorizontalGroup(
            PanelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLaporanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, 388, Short.MAX_VALUE)
                    .addGroup(PanelLaporanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLaporanLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelLaporanLayout.setVerticalGroup(
            PanelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLaporanLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        MainPanel.add(PanelLaporan, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jComboBox1.getSelectedItem().equals("Pilih Nama Laporan")) {
            JOptionPane.showMessageDialog(null, "Pilih Laporan yang Ingin di Cetak");
        }else if (jComboBox1.getSelectedItem().equals("Data Barang")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataBarang.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else if (jComboBox1.getSelectedItem().equals("Data Merek")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataMerek.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else if (jComboBox1.getSelectedItem().equals("Data Jenis")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataJenis.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else if (jComboBox1.getSelectedItem().equals("Data Supplier")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataSupplier.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else if (jComboBox1.getSelectedItem().equals("Data User")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataUser.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else if (jComboBox1.getSelectedItem().equals("Data Barang Masuk")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataBarangMasuk.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else if (jComboBox1.getSelectedItem().equals("Data Barang Keluar")) {
            try {
                JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("DataBarangKeluar.jasper"), null, Koneksi.KoneksiD.BukaKoneksi());
                JasperViewer.viewReport(jp, false);
            } catch(Exception e) {
                System.err.println("Error : " + e.getMessage());
            } 
        }else{
            JOptionPane.showMessageDialog(null, "Tidak Ada Laporan Tersebut");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PanelLaporan;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
