/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Transaksi;

import java.awt.event.ActionEvent;
import java.util.Date;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmuzaki.a
 */
public class FormMasuk extends javax.swing.JPanel {

    /**
     * Creates new form FormMasuk
     */
    
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormMasuk() {
        initComponents();
        hari();
        isitabel();
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        cbb_barang();
        cbb_supplier();
    }

    private void hari() {
        Date now = new Date();
        SimpleDateFormat tanggal = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = tanggal.format(now);
        TextTanggal.setText(tgl);
        TextTanggal.setEditable(false);
    }
    
    private void bersih() {
        TextIDMasuk.setText("");
        ComboBoxBarang.setSelectedItem("Pilih Nama Barang");
        TextStok.setText("");
        ComboBoxSupplier.setSelectedItem("Pilih Nama Supplier");
        TextUser.setText("");
    }
    
    private void isitabel() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM brng_masuk");
            
            DefaultTableModel model = new DefaultTableModel();
                TableMasuk.setModel(model);
                model.addColumn("ID Masuk");
                model.addColumn("Tanggal Masuk");
                model.addColumn("Nama Barang");
                model.addColumn("Stok Masuk");
                model.addColumn("Nama Supplier");
                model.addColumn("Nama Petugas");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_masuk"),
                  rs.getString("tgl_masuk"),
                  rs.getString("nm_barang"),
                  rs.getString("stok_masuk"),
                  rs.getString("nm_supplier"),
                  rs.getString("nm_user")
                };
                model.addRow(data);
                //TableBrng.setModel(model);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    
    private void cbb_barang() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM barang");
            
            while (rs.next()) {
                String jns = rs.getString("nm_barang");
                ComboBoxBarang.addItem(jns);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
        
    }
    
    private void cbb_supplier() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM supplier");
            
            while (rs.next()) {
                String jns = rs.getString("nm_supplier");
                ComboBoxSupplier.addItem(jns);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelMasuk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMasuk = new javax.swing.JTable();
        PanelTambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnTambah1 = new javax.swing.JButton();
        BtnHapus1 = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        IDMasuk = new javax.swing.JLabel();
        TextIDMasuk = new javax.swing.JTextField();
        TanggalMasuk = new javax.swing.JLabel();
        TextTanggal = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JLabel();
        ComboBoxBarang = new javax.swing.JComboBox<>();
        StokMasuk = new javax.swing.JLabel();
        TextStok = new javax.swing.JTextField();
        NamaSupplier = new javax.swing.JLabel();
        ComboBoxSupplier = new javax.swing.JComboBox<>();
        NamaPetugas = new javax.swing.JLabel();
        TextUser = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        PanelMasuk.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA BARANG MASUK");

        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TableMasuk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Masuk", "Tanggal Masuk", "Nama Barang", "Stok Masuk", "Nama Supplier", "Nama Petugas"
            }
        ));
        TableMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMasukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMasuk);

        javax.swing.GroupLayout PanelMasukLayout = new javax.swing.GroupLayout(PanelMasuk);
        PanelMasuk.setLayout(PanelMasukLayout);
        PanelMasukLayout.setHorizontalGroup(
            PanelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelMasukLayout.createSequentialGroup()
                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMasukLayout.setVerticalGroup(
            PanelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMasukLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(PanelMasuk, "card2");

        PanelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA TAMBAH BARANG MASUK");

        BtnTambah1.setText("TAMBAH");
        BtnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambah1ActionPerformed(evt);
            }
        });

        BtnHapus1.setText("HAPUS");
        BtnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapus1ActionPerformed(evt);
            }
        });

        BtnBatal1.setText("BATAL");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        IDMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDMasuk.setText("ID Masuk");

        TextIDMasuk.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        TanggalMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TanggalMasuk.setText("Tanggal Masuk");

        TextTanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaBarang.setText("Nama_Barang");

        ComboBoxBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Barang" }));

        StokMasuk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StokMasuk.setText("Stok Masuk");

        TextStok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaSupplier.setText("Nama Supplier");

        ComboBoxSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Supplier" }));

        NamaPetugas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaPetugas.setText("Nama Petugas");

        TextUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelTambahLayout = new javax.swing.GroupLayout(PanelTambah);
        PanelTambah.setLayout(PanelTambahLayout);
        PanelTambahLayout.setHorizontalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIDMasuk)
                    .addComponent(TextTanggal)
                    .addComponent(TextStok, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(TextUser, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(ComboBoxBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelTambahLayout.createSequentialGroup()
                        .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDMasuk)
                            .addComponent(TanggalMasuk)
                            .addComponent(NamaBarang)
                            .addComponent(StokMasuk)
                            .addComponent(NamaSupplier)
                            .addComponent(NamaPetugas)
                            .addGroup(PanelTambahLayout.createSequentialGroup()
                                .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTambahLayout.setVerticalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanggalMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StokMasuk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextStok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaSupplier)
                .addGap(8, 8, 8)
                .addComponent(ComboBoxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaPetugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTambah, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelTambah);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (BtnTambah.getText() == "UBAH") {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
            jLabel2.setText("UBAH DATA BARANG MASUK");
            BtnTambah1.setText("SIMPAN");
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Menghapus Data", "Message", JOptionPane.YES_NO_OPTION);
            if (a==0) {
                try {
                    stmt = con.createStatement();
                    String hapus = "DELETE FROM brng_masuk WHERE id_masuk = '" + TextIDMasuk.getText() + "'";
                    stmt.executeUpdate(hapus);  
                    
                    isitabel();
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    BtnTambah.setText("TAMBAH");
                    BtnHapus.setVisible(false);
                    BtnBatal.setVisible(false);                   
                    
                    bersih();
                    BtnHapus1.setVisible(true);
                    TextIDMasuk.setEditable(true);
                } catch (Exception e) {
                    System.err.println("Error : " + e.getMessage());
                }
                
            }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        
        BtnTambah.setText("TAMBAH");
        
        jLabel2.setText("TAMBAH DATA BARANG MASUK");
        TextIDMasuk.setEditable(true);        
        BtnTambah1.setText("TAMBAH");
        BtnHapus1.setVisible(true);
        
        bersih();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambah1ActionPerformed
        try {
            stmt = con.createStatement();
            if(TextIDMasuk.getText().equals("") || ComboBoxBarang.getSelectedItem().equals("Pilih Nama Barang") || 
                    TextStok.getText().equals("") || ComboBoxSupplier.getSelectedItem().equals("Pilih Nama Supplier") ||
                    TextUser.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu");
                return;
            }
            
            //simpan
            if (BtnTambah1.getText() == "TAMBAH") {
                String cek = "SELECT * FROM brng_masuk WHERE id_masuk = '" + TextIDMasuk.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ID User ini Sudah Ada");
                }else{
                    String sql = "INSERT INTO brng_masuk VALUES ('" + TextIDMasuk.getText() + 
                        "','" + TextTanggal.getText() + "','" + ComboBoxBarang.getSelectedItem() + 
                        "','" + TextStok.getText() + "','" + ComboBoxSupplier.getSelectedItem() + 
                        "','" + TextUser.getText() + "')";
                    stmt.executeUpdate(sql);                
                
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                    bersih();
                    isitabel();
                    
                    MainPanel.removeAll();
                    MainPanel.repaint();
                    MainPanel.revalidate();
        
                    MainPanel.add(PanelMasuk);
                    MainPanel.repaint();
                    MainPanel.revalidate();
                }
            }else{
                String update = "UPDATE brng_masuk SET tgl_masuk = '" + TextTanggal.getText() +
                    "', nm_barang = '" + ComboBoxBarang.getSelectedItem() +
                    "', stok_masuk = '" + TextStok.getText() +
                    "', nm_supplier = '" + ComboBoxSupplier.getSelectedItem() +
                    "', nm_user = '" + TextUser.getText() +
                    "' WHERE id_masuk = '" + TextIDMasuk.getText() + "'";
                stmt.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
                bersih();
                isitabel();
                
                BtnHapus.setVisible(false);
                BtnBatal.setVisible(false);
                jLabel2.setText("TAMBAH DATA BARANG MASUK");
                BtnTambah.setText("TAMBAH");
                
                BtnTambah1.setText("TAMBAH");
                BtnHapus1.setVisible(true);
        
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
        
                MainPanel.add(PanelMasuk);
                MainPanel.repaint();
                MainPanel.revalidate();
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_BtnTambah1ActionPerformed

    private void BtnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapus1ActionPerformed
        bersih();
    }//GEN-LAST:event_BtnHapus1ActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelMasuk);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        bersih();
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void TableMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMasukMouseClicked
        BtnTambah.setText("UBAH");
        BtnHapus.setVisible(true);
        BtnBatal.setVisible(true);
        BtnHapus1.setVisible(false);
        
            TextIDMasuk.setText(TableMasuk.getValueAt(TableMasuk.getSelectedRow(), 0).toString());
            TextTanggal.setText(TableMasuk.getValueAt(TableMasuk.getSelectedRow(), 1).toString());
            ComboBoxBarang.setSelectedItem(TableMasuk.getValueAt(TableMasuk.getSelectedRow(), 2).toString());
            TextStok.setText(TableMasuk.getValueAt(TableMasuk.getSelectedRow(), 3).toString());
            ComboBoxSupplier.setSelectedItem(TableMasuk.getValueAt(TableMasuk.getSelectedRow(), 4).toString());
            TextUser.setText(TableMasuk.getValueAt(TableMasuk.getSelectedRow(), 5).toString());
            
            TextIDMasuk.setEditable(false);
    }//GEN-LAST:event_TableMasukMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBatal1;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHapus1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambah1;
    private javax.swing.JComboBox<String> ComboBoxBarang;
    private javax.swing.JComboBox<String> ComboBoxSupplier;
    private javax.swing.JLabel IDMasuk;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JLabel NamaPetugas;
    private javax.swing.JLabel NamaSupplier;
    private javax.swing.JPanel PanelMasuk;
    private javax.swing.JPanel PanelTambah;
    private javax.swing.JLabel StokMasuk;
    private javax.swing.JTable TableMasuk;
    private javax.swing.JLabel TanggalMasuk;
    private javax.swing.JTextField TextIDMasuk;
    private javax.swing.JTextField TextStok;
    private javax.swing.JTextField TextTanggal;
    private javax.swing.JTextField TextUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
