/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Transaksi;

import java.awt.event.ActionEvent;
import java.util.Date;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmuzaki.a
 */
public class FormKeluar extends javax.swing.JPanel {

    /**
     * Creates new form FormKeluar
     */
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormKeluar() {
        initComponents();
        hari();
        isitabel();
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        cbb_barang();
    }

    private void hari() {
        Date now = new Date();
        SimpleDateFormat tanggal = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = tanggal.format(now);
        TextTanggal.setText(tgl);
        TextTanggal.setEditable(false);
    }
    
    private void bersih() {
        TextIDKeluar.setText("");
        ComboBoxBarang.setSelectedItem("Pilih Nama Barang");
        TextStok.setText("");
        TextUser.setText("");
    }
    
    private void isitabel() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM brng_keluar");
            
            DefaultTableModel model = new DefaultTableModel();
                TableKeluar.setModel(model);
                model.addColumn("ID Keluar");
                model.addColumn("Tanggal Keluar");
                model.addColumn("Nama Barang");
                model.addColumn("Stok Keluar");
                model.addColumn("Nama Petugas");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_keluar"),
                  rs.getString("tgl_keluar"),
                  rs.getString("nm_barang"),
                  rs.getString("stok_keluar"),
                  rs.getString("nm_user")
                };
                model.addRow(data);
                //TableBrng.setModel(model);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    
    private void cbb_barang() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM barang");
            
            while (rs.next()) {
                String jns = rs.getString("nm_barang");
                ComboBoxBarang.addItem(jns);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelKeluar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKeluar = new javax.swing.JTable();
        PanelTambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnTambah1 = new javax.swing.JButton();
        BtnHapus1 = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        IDKeluar = new javax.swing.JLabel();
        TextIDKeluar = new javax.swing.JTextField();
        TanggalKeluar = new javax.swing.JLabel();
        TextTanggal = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JLabel();
        ComboBoxBarang = new javax.swing.JComboBox<>();
        StokKeluar = new javax.swing.JLabel();
        TextStok = new javax.swing.JTextField();
        NamaUser = new javax.swing.JLabel();
        TextUser = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        PanelKeluar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA BARANG KELUAR");

        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TableKeluar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Keluar", "Tanggal Keluar", "Nama Barang", "Stok Keluar", "Nama Petugas"
            }
        ));
        TableKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableKeluarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableKeluar);

        javax.swing.GroupLayout PanelKeluarLayout = new javax.swing.GroupLayout(PanelKeluar);
        PanelKeluar.setLayout(PanelKeluarLayout);
        PanelKeluarLayout.setHorizontalGroup(
            PanelKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelKeluarLayout.createSequentialGroup()
                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelKeluarLayout.setVerticalGroup(
            PanelKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelKeluarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(PanelKeluar, "card2");

        PanelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA TAMBAH BARANG KELUAR");

        BtnTambah1.setText("TAMBAH");
        BtnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambah1ActionPerformed(evt);
            }
        });

        BtnHapus1.setText("HAPUS");
        BtnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapus1ActionPerformed(evt);
            }
        });

        BtnBatal1.setText("BATAL");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        IDKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDKeluar.setText("ID Keluar");

        TextIDKeluar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        TanggalKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TanggalKeluar.setText("Tanggal Keluar");

        TextTanggal.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaBarang.setText("Nama_Barang");

        ComboBoxBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Barang" }));

        StokKeluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StokKeluar.setText("Stok Keluar");

        TextStok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaUser.setText("Nama User");

        TextUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelTambahLayout = new javax.swing.GroupLayout(PanelTambah);
        PanelTambah.setLayout(PanelTambahLayout);
        PanelTambahLayout.setHorizontalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIDKeluar)
                    .addComponent(TextTanggal)
                    .addComponent(TextStok)
                    .addComponent(ComboBoxBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextUser)
                    .addGroup(PanelTambahLayout.createSequentialGroup()
                        .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTambahLayout.createSequentialGroup()
                                .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDKeluar)
                            .addComponent(TanggalKeluar)
                            .addComponent(NamaBarang)
                            .addComponent(StokKeluar)
                            .addComponent(NamaUser))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTambahLayout.setVerticalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TanggalKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StokKeluar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextStok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTambah, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelTambah);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (BtnTambah.getText() == "UBAH") {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
            jLabel2.setText("UBAH DATA BARANG KELUAR");
            BtnTambah1.setText("SIMPAN");
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Menghapus Data", "Message", JOptionPane.YES_NO_OPTION);
            if (a==0) {
                try {
                    stmt = con.createStatement();
                    String hapus = "DELETE FROM brng_keluar WHERE id_keluar = '" + TextIDKeluar.getText() + "'";
                    stmt.executeUpdate(hapus);  
                    
                    isitabel();
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    BtnTambah.setText("TAMBAH");
                    BtnHapus.setVisible(false);
                    BtnBatal.setVisible(false);                   
                    
                    bersih();
                    BtnHapus1.setVisible(true);
                    TextIDKeluar.setEditable(true);
                } catch (Exception e) {
                    System.err.println("Error : " + e.getMessage());
                }
                
            }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        
        BtnTambah.setText("TAMBAH");
        
        jLabel2.setText("TAMBAH DATA BARANG KELUAR");
        TextIDKeluar.setEditable(true);        
        BtnTambah1.setText("TAMBAH");
        BtnHapus1.setVisible(true);
        
        bersih();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambah1ActionPerformed
        try {
            stmt = con.createStatement();
            if(TextIDKeluar.getText().equals("") || ComboBoxBarang.getSelectedItem().equals("Pilih Nama Barang") || 
                    TextStok.getText().equals("") || TextUser.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu");
                return;
            }
            
            //simpan
            if (BtnTambah1.getText() == "TAMBAH") {
                String cek = "SELECT * FROM brng_keluar WHERE id_keluar = '" + TextIDKeluar.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ID User ini Sudah Ada");
                }else{
                    String sql = "INSERT INTO brng_keluar VALUES ('" + TextIDKeluar.getText() + 
                        "','" + TextTanggal.getText() + "','" + ComboBoxBarang.getSelectedItem() + 
                        "','" + TextStok.getText() + "','" + TextUser.getText() + "')";
                    stmt.executeUpdate(sql);                
                
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                    bersih();
                    isitabel();
                    
                    MainPanel.removeAll();
                    MainPanel.repaint();
                    MainPanel.revalidate();
        
                    MainPanel.add(PanelKeluar);
                    MainPanel.repaint();
                    MainPanel.revalidate();
                }
            }else{
                String update = "UPDATE brng_keluar SET tgl_keluar = '" + TextTanggal.getText() +
                    "', nm_barang = '" + ComboBoxBarang.getSelectedItem() +
                    "', stok_keluar = '" + TextStok.getText() +
                    "', nm_user = '" + TextUser.getText() +
                    "' WHERE id_keluar = '" + TextIDKeluar.getText() + "'";
                stmt.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
                bersih();
                isitabel();
                
                BtnHapus.setVisible(false);
                BtnBatal.setVisible(false);
                jLabel2.setText("TAMBAH DATA BARANG MASUK");
                BtnTambah.setText("TAMBAH");
                
                BtnTambah1.setText("TAMBAH");
                BtnHapus1.setVisible(true);
        
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
        
                MainPanel.add(PanelKeluar);
                MainPanel.repaint();
                MainPanel.revalidate();
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_BtnTambah1ActionPerformed

    private void BtnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapus1ActionPerformed
        bersih();
    }//GEN-LAST:event_BtnHapus1ActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelKeluar);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        bersih();
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void TableKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableKeluarMouseClicked
        BtnTambah.setText("UBAH");
        BtnHapus.setVisible(true);
        BtnBatal.setVisible(true);
        BtnHapus1.setVisible(false);
        
            TextIDKeluar.setText(TableKeluar.getValueAt(TableKeluar.getSelectedRow(), 0).toString());
            TextTanggal.setText(TableKeluar.getValueAt(TableKeluar.getSelectedRow(), 1).toString());
            ComboBoxBarang.setSelectedItem(TableKeluar.getValueAt(TableKeluar.getSelectedRow(), 2).toString());
            TextStok.setText(TableKeluar.getValueAt(TableKeluar.getSelectedRow(), 3).toString());
            TextUser.setText(TableKeluar.getValueAt(TableKeluar.getSelectedRow(), 4).toString());
            
            TextIDKeluar.setEditable(false);
    }//GEN-LAST:event_TableKeluarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBatal1;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHapus1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambah1;
    private javax.swing.JComboBox<String> ComboBoxBarang;
    private javax.swing.JLabel IDKeluar;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JLabel NamaUser;
    private javax.swing.JPanel PanelKeluar;
    private javax.swing.JPanel PanelTambah;
    private javax.swing.JLabel StokKeluar;
    private javax.swing.JTable TableKeluar;
    private javax.swing.JLabel TanggalKeluar;
    private javax.swing.JTextField TextIDKeluar;
    private javax.swing.JTextField TextStok;
    private javax.swing.JTextField TextTanggal;
    private javax.swing.JTextField TextUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
