/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import DropdownMenu.MenuEvent;
import Laporan.FormLaporan;
import Master.FormBarang;
import Master.FormJenis;
import Master.FormMerek;
import Master.FormSupplier;
import Transaksi.FormKeluar;
import Transaksi.FormMasuk;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mmuzaki.a
 */
public class FormMenuStaff extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuStaff
     */
    public FormMenuStaff() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        menuStaff2.setEvent(new MenuEvent() {
           @Override
           public void selected(int index, int subIndex) {
               if(index==0){
                   showForm(new Home());
               }else if (index==1 && subIndex==1) {
                   showForm(new FormBarang());
               }else if (index==1 && subIndex==2) {
                   showForm(new FormJenis());
               }else if (index==1 && subIndex==3) {
                   showForm(new FormMerek());
               }else if (index==1 && subIndex==4) {
                   showForm(new FormSupplier());
               }else if (index==2 && subIndex==1) {
                   showForm(new FormMasuk());
               }else if (index==2 && subIndex==2) {
                   showForm(new FormKeluar());
               }else if (index==3) {
                   showForm(new FormLaporan());
               }else if (index==4) {
                   int a=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin keluar", "select", JOptionPane.YES_NO_OPTION);
                    if (a==0) {
                        dispose(); // Jika pengguna memilih "Yes" (0), keluar dari aplikasi
                        new FormLogin().setVisible(true);
                    }              
               }else{
                   showForm(new DefaultForm("Form : "+index+ " " +subIndex)); 
               }   
           }
        });
    }

    private void showForm(Component com) {
        PanelUtama.removeAll();
        PanelUtama.add(com);
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelNavbar = new javax.swing.JPanel();
        PanelSideBar = new javax.swing.JPanel();
        scrollPaneWin111 = new DropdownMenu.ScrollPaneWin11();
        menuStaff2 = new DropdownMenu.MenuStaff();
        PanelContent = new javax.swing.JPanel();
        PanelUtama = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelNavbar.setBackground(new java.awt.Color(255, 255, 204));
        PanelNavbar.setPreferredSize(new java.awt.Dimension(750, 70));

        javax.swing.GroupLayout PanelNavbarLayout = new javax.swing.GroupLayout(PanelNavbar);
        PanelNavbar.setLayout(PanelNavbarLayout);
        PanelNavbarLayout.setHorizontalGroup(
            PanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        PanelNavbarLayout.setVerticalGroup(
            PanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(PanelNavbar, java.awt.BorderLayout.PAGE_START);

        PanelSideBar.setBackground(new java.awt.Color(204, 255, 204));
        PanelSideBar.setPreferredSize(new java.awt.Dimension(250, 380));

        scrollPaneWin111.setViewportView(menuStaff2);

        javax.swing.GroupLayout PanelSideBarLayout = new javax.swing.GroupLayout(PanelSideBar);
        PanelSideBar.setLayout(PanelSideBarLayout);
        PanelSideBarLayout.setHorizontalGroup(
            PanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        PanelSideBarLayout.setVerticalGroup(
            PanelSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        getContentPane().add(PanelSideBar, java.awt.BorderLayout.LINE_START);

        PanelContent.setBackground(new java.awt.Color(204, 255, 255));

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanelContentLayout = new javax.swing.GroupLayout(PanelContent);
        PanelContent.setLayout(PanelContentLayout);
        PanelContentLayout.setHorizontalGroup(
            PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        PanelContentLayout.setVerticalGroup(
            PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showForm(new Home());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private javax.swing.JPanel PanelNavbar;
    private javax.swing.JPanel PanelSideBar;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel jPanel2;
    private DropdownMenu.MenuStaff menuStaff2;
    private DropdownMenu.ScrollPaneWin11 scrollPaneWin111;
    // End of variables declaration//GEN-END:variables
}
