/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import DropdownMenu.MenuEvent;
import Laporan.FormLaporan;
import Master.FormBarang;
import Master.FormJenis;
import Master.FormMerek;
import Master.FormSupplier;
import Master.FormUser;
import Transaksi.FormKeluar;
import Transaksi.FormMasuk;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.lang.String;

/**
 *
 * @author mmuzaki.a
 */
public class FormMenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FormMenuAdmin
     */
    public FormMenuAdmin(String nama, String level) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        jLabel1.setText(nama);
        jLabel2.setText(level);
        
        menu1.setEvent(new MenuEvent() {
           @Override
           public void selected(int index, int subIndex) {
               if(index==0){
                   showForm(new Home());
               }else if (index==1 && subIndex==1) {
                   showForm(new FormBarang());
               }else if (index==1 && subIndex==2) {
                   showForm(new FormJenis());
               }else if (index==1 && subIndex==3) {
                   showForm(new FormMerek());
               }else if (index==1 && subIndex==4) {
                   showForm(new FormSupplier());
               }else if (index==1 && subIndex==5) {
                   showForm(new FormUser());    
               }else if (index==2 && subIndex==1) {
                   showForm(new FormMasuk());
               }else if (index==2 && subIndex==2) {
                   showForm(new FormKeluar());
               }else if (index==3) {
                   showForm(new FormLaporan());
               }else if (index==4) {
                   int a=JOptionPane.showConfirmDialog(null,"Apakah yakin ingin keluar", "select", JOptionPane.YES_NO_OPTION);
                    if (a==0) {
                        dispose(); // Jika pengguna memilih "Yes" (0), keluar dari aplikasi
                        new FormLogin().setVisible(true);
                    }              
               }else{
                   showForm(new DefaultForm("Form : "+index+ " " +subIndex)); 
               }    
           }
        });
        
    }

    private void showForm(Component com) {
        PanelUtama.removeAll();
        PanelUtama.add(com);
        PanelUtama.repaint();
        PanelUtama.revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelNavbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PanelSidebar = new javax.swing.JPanel();
        scrollPaneWin111 = new DropdownMenu.ScrollPaneWin11();
        menu1 = new DropdownMenu.Menu();
        PanelContent = new javax.swing.JPanel();
        PanelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PanelNavbar.setBackground(new java.awt.Color(255, 255, 255));
        PanelNavbar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelNavbar.setPreferredSize(new java.awt.Dimension(750, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Level");

        javax.swing.GroupLayout PanelNavbarLayout = new javax.swing.GroupLayout(PanelNavbar);
        PanelNavbar.setLayout(PanelNavbarLayout);
        PanelNavbarLayout.setHorizontalGroup(
            PanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelNavbarLayout.setVerticalGroup(
            PanelNavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNavbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(PanelNavbar, java.awt.BorderLayout.PAGE_START);

        PanelSidebar.setBackground(new java.awt.Color(0, 0, 0));
        PanelSidebar.setPreferredSize(new java.awt.Dimension(250, 380));

        scrollPaneWin111.setViewportView(menu1);

        javax.swing.GroupLayout PanelSidebarLayout = new javax.swing.GroupLayout(PanelSidebar);
        PanelSidebar.setLayout(PanelSidebarLayout);
        PanelSidebarLayout.setHorizontalGroup(
            PanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        PanelSidebarLayout.setVerticalGroup(
            PanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPaneWin111, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        getContentPane().add(PanelSidebar, java.awt.BorderLayout.LINE_START);

        PanelContent.setBackground(new java.awt.Color(0, 0, 0));

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        PanelUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanelContentLayout = new javax.swing.GroupLayout(PanelContent);
        PanelContent.setLayout(PanelContentLayout);
        PanelContentLayout.setHorizontalGroup(
            PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelContentLayout.setVerticalGroup(
            PanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(PanelContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        showForm(new Home());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenuAdmin("nama", "level").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private javax.swing.JPanel PanelNavbar;
    private javax.swing.JPanel PanelSidebar;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private DropdownMenu.Menu menu1;
    private DropdownMenu.ScrollPaneWin11 scrollPaneWin111;
    // End of variables declaration//GEN-END:variables
}
