/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Master;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmuzaki.a
 */
public class FormUser extends javax.swing.JPanel {

    /**
     * Creates new form FormUser
     */
    
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormUser() {
        initComponents();
        isitabel();
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
    }

    private void bersih() {
        TextIDUser.setText("");
        ComboBoxLevel.setSelectedItem("Pilih Level User");
        TextNama.setText("");        
        TextUser.setText("");
        TextPass.setText("");
        TextNoHP.setText("");
        TextAlamat.setText("");
    }
    
    private void isitabel() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM user");
            
            DefaultTableModel model = new DefaultTableModel();
                TableUser.setModel(model);
                model.addColumn("ID User");
                model.addColumn("Level");
                model.addColumn("Nama Petugas");
                model.addColumn("Username");
                model.addColumn("Password");
                model.addColumn("Nomor HP");
                model.addColumn("Alamat");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_user"),
                  rs.getString("lvl_user"),
                  rs.getString("nm_user"),
                  rs.getString("username"),
                  rs.getString("password"),
                  rs.getString("nohp_user"),
                  rs.getString("alamat_user")
                };
                model.addRow(data);
                //TableBrng.setModel(model);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelUser = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        PanelTambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnTambah1 = new javax.swing.JButton();
        BtnHapus1 = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        IDUser = new javax.swing.JLabel();
        TextIDUser = new javax.swing.JTextField();
        Level = new javax.swing.JLabel();
        ComboBoxLevel = new javax.swing.JComboBox<>();
        NamaPetugas = new javax.swing.JLabel();
        TextNama = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        TextUser = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        TextPass = new javax.swing.JTextField();
        NoHp = new javax.swing.JLabel();
        TextNoHP = new javax.swing.JTextField();
        TextAlamat = new javax.swing.JTextField();
        Alamat = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        PanelUser.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA USER");

        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID User", "Level", "Nama Petugas", "Username", "Password", "Nomor HP", "Alamat"
            }
        ));
        TableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableUser);

        javax.swing.GroupLayout PanelUserLayout = new javax.swing.GroupLayout(PanelUser);
        PanelUser.setLayout(PanelUserLayout);
        PanelUserLayout.setHorizontalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelUserLayout.createSequentialGroup()
                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelUserLayout.setVerticalGroup(
            PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(PanelUser, "card2");

        PanelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH DATA USER");

        BtnTambah1.setText("TAMBAH");
        BtnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambah1ActionPerformed(evt);
            }
        });

        BtnHapus1.setText("HAPUS");
        BtnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapus1ActionPerformed(evt);
            }
        });

        BtnBatal1.setText("BATAL");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        IDUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDUser.setText("ID User");

        TextIDUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Level.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Level.setText("Level");

        ComboBoxLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Level User", "Staff", "Admin" }));

        NamaPetugas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaPetugas.setText("Nama Petugas");

        TextNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Username.setText("Username");

        TextUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setText("Password");

        TextPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NoHp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoHp.setText("Nomor HP");

        TextNoHP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        TextAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Alamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Alamat.setText("Alamat");

        javax.swing.GroupLayout PanelTambahLayout = new javax.swing.GroupLayout(PanelTambah);
        PanelTambah.setLayout(PanelTambahLayout);
        PanelTambahLayout.setHorizontalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIDUser)
                    .addComponent(TextNama, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(TextUser, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(TextPass, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(TextNoHP, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(TextAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(PanelTambahLayout.createSequentialGroup()
                        .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTambahLayout.createSequentialGroup()
                                .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDUser)
                            .addComponent(Level)
                            .addComponent(NamaPetugas)
                            .addComponent(Username)
                            .addComponent(Password)
                            .addComponent(NoHp)
                            .addComponent(Alamat))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ComboBoxLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelTambahLayout.setVerticalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Level)
                .addGap(8, 8, 8)
                .addComponent(ComboBoxLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaPetugas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoHp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTambah, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelTambah);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (BtnTambah.getText() == "UBAH") {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
            jLabel2.setText("UBAH DATA USER");
            BtnTambah1.setText("SIMPAN");
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Menghapus Data", "Message", JOptionPane.YES_NO_OPTION);
            if (a==0) {
                try {
                    stmt = con.createStatement();
                    String hapus = "DELETE FROM user WHERE id_user = '" + TextIDUser.getText() + "'";
                    stmt.executeUpdate(hapus);  
                    
                    isitabel();
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    BtnTambah.setText("TAMBAH");
                    BtnHapus.setVisible(false);
                    BtnBatal.setVisible(false);                   
                    
                    bersih();
                    BtnHapus1.setVisible(true);
                    TextIDUser.setEditable(true);
                } catch (Exception e) {
                    System.err.println("Error : " + e.getMessage());
                }
                
            }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        
        BtnTambah.setText("TAMBAH");
        
        jLabel2.setText("TAMBAH DATA USER");
        TextIDUser.setEditable(true);        
        BtnTambah1.setText("TAMBAH");
        BtnHapus1.setVisible(true);
        
        bersih();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambah1ActionPerformed
        try {
            stmt = con.createStatement();
            if(TextIDUser.getText().equals("") || ComboBoxLevel.getSelectedItem().equals("Pilih Level User") || 
                    TextNama.getText().equals("") || TextUser.getText().equals("") ||
                    TextPass.getText().equals("") || TextNoHP.getText().equals("") ||
                    TextAlamat.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu");
                return;
            }
            
            //simpan
            if (BtnTambah1.getText() == "TAMBAH") {
                String cek = "SELECT * FROM user WHERE id_user = '" + TextIDUser.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ID User ini Sudah Ada");
                }else{
                    String sql = "INSERT INTO user VALUES ('" + TextIDUser.getText() + 
                        "','" + ComboBoxLevel.getSelectedItem() + "','" + TextNama.getText() + 
                        "','" + TextUser.getText() + "','" + TextPass.getText() + 
                        "','" + TextNoHP.getText() + "','" + TextAlamat.getText() + "')";
                    stmt.executeUpdate(sql);                
                
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                    bersih();
                    isitabel();
                    
                    MainPanel.removeAll();
                    MainPanel.repaint();
                    MainPanel.revalidate();
        
                    MainPanel.add(PanelUser);
                    MainPanel.repaint();
                    MainPanel.revalidate();
                }
            }else{
                String update = "UPDATE user SET lvl_user = '" + ComboBoxLevel.getSelectedItem() +
                    "', nm_user = '" + TextNama.getText() +
                    "', username = '" + TextUser.getText() +
                    "', password = '" + TextPass.getText() +
                    "', nohp_user = '" + TextNoHP.getText() +
                    "', alamat_user = '" + TextAlamat.getText() +
                    "' WHERE id_user = '" + TextIDUser.getText() + "'";
                stmt.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
                bersih();
                isitabel();
                
                BtnHapus.setVisible(false);
                BtnBatal.setVisible(false);
                jLabel2.setText("TAMBAH DATA USER");
                BtnTambah.setText("TAMBAH");
                
                BtnTambah1.setText("TAMBAH");
                BtnHapus1.setVisible(true);
        
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
        
                MainPanel.add(PanelTambah);
                MainPanel.repaint();
                MainPanel.revalidate();
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_BtnTambah1ActionPerformed

    private void BtnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapus1ActionPerformed
        bersih();
    }//GEN-LAST:event_BtnHapus1ActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelUser);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        bersih();
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void TableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableUserMouseClicked
        BtnTambah.setText("UBAH");
        BtnHapus.setVisible(true);
        BtnBatal.setVisible(true);
        BtnHapus1.setVisible(false);
        
            TextIDUser.setText(TableUser.getValueAt(TableUser.getSelectedRow(), 0).toString());
            ComboBoxLevel.setSelectedItem(TableUser.getValueAt(TableUser.getSelectedRow(), 1).toString());
            TextNama.setText(TableUser.getValueAt(TableUser.getSelectedRow(), 2).toString());
            TextUser.setText(TableUser.getValueAt(TableUser.getSelectedRow(), 3).toString());
            TextPass.setText(TableUser.getValueAt(TableUser.getSelectedRow(), 4).toString());
            TextNoHP.setText(TableUser.getValueAt(TableUser.getSelectedRow(), 5).toString());
            TextAlamat.setText(TableUser.getValueAt(TableUser.getSelectedRow(), 6).toString());
            
            TextIDUser.setEditable(false);
    }//GEN-LAST:event_TableUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBatal1;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHapus1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambah1;
    private javax.swing.JComboBox<String> ComboBoxLevel;
    private javax.swing.JLabel IDUser;
    private javax.swing.JLabel Level;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaPetugas;
    private javax.swing.JLabel NoHp;
    private javax.swing.JPanel PanelTambah;
    private javax.swing.JPanel PanelUser;
    private javax.swing.JLabel Password;
    private javax.swing.JTable TableUser;
    private javax.swing.JTextField TextAlamat;
    private javax.swing.JTextField TextIDUser;
    private javax.swing.JTextField TextNama;
    private javax.swing.JTextField TextNoHP;
    private javax.swing.JTextField TextPass;
    private javax.swing.JTextField TextUser;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
