/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Master;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmuzaki.a
 */
public class FormSupplier extends javax.swing.JPanel {

    /**
     * Creates new form FormSupplier
     */
    
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormSupplier() {
        initComponents();
        isitabel();
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
    }

    private void bersih() {
        TextIDSupplier.setText("");
        TextNama.setText("");
        TextNoHP.setText("");
        TextAlamat.setText("");
    }
    
    private void isitabel() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM supplier");
            
            DefaultTableModel model = new DefaultTableModel();
                TableSupplier.setModel(model);
                model.addColumn("ID Supplier");
                model.addColumn("Nama Supplier");
                model.addColumn("Nomor HP");
                model.addColumn("Alamat");
                
                
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_supplier"),
                  rs.getString("nm_supplier"),
                  rs.getString("nohp_supplier"),
                  rs.getString("alamat_supplier"),
                };
                model.addRow(data);
            }
            
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelSupplier = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSupplier = new javax.swing.JTable();
        PanelTambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnTambah1 = new javax.swing.JButton();
        BtnHapus1 = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        IDSupplier = new javax.swing.JLabel();
        TextIDSupplier = new javax.swing.JTextField();
        NamaSupplier = new javax.swing.JLabel();
        TextNama = new javax.swing.JTextField();
        NoHp = new javax.swing.JLabel();
        TextNoHP = new javax.swing.JTextField();
        Alamat = new javax.swing.JLabel();
        TextAlamat = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        PanelSupplier.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA SUPPLIER");

        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TableSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Supplier", "Nama Supplier", "Nomor HP", "Alamat"
            }
        ));
        TableSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSupplier);

        javax.swing.GroupLayout PanelSupplierLayout = new javax.swing.GroupLayout(PanelSupplier);
        PanelSupplier.setLayout(PanelSupplierLayout);
        PanelSupplierLayout.setHorizontalGroup(
            PanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelSupplierLayout.createSequentialGroup()
                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSupplierLayout.setVerticalGroup(
            PanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSupplierLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(PanelSupplier, "card2");

        PanelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH DATA SUPPLIER");

        BtnTambah1.setText("TAMBAH");
        BtnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambah1ActionPerformed(evt);
            }
        });

        BtnHapus1.setText("HAPUS");
        BtnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapus1ActionPerformed(evt);
            }
        });

        BtnBatal1.setText("BATAL");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        IDSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDSupplier.setText("ID Supplier");

        TextIDSupplier.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaSupplier.setText("Nama Supplier");

        TextNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NoHp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NoHp.setText("Nomor HP");

        TextNoHP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        Alamat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Alamat.setText("Alamat");

        TextAlamat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelTambahLayout = new javax.swing.GroupLayout(PanelTambah);
        PanelTambah.setLayout(PanelTambahLayout);
        PanelTambahLayout.setHorizontalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIDSupplier)
                    .addComponent(TextNama)
                    .addComponent(TextNoHP)
                    .addComponent(TextAlamat)
                    .addGroup(PanelTambahLayout.createSequentialGroup()
                        .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTambahLayout.createSequentialGroup()
                                .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDSupplier)
                            .addComponent(NamaSupplier)
                            .addComponent(NoHp)
                            .addComponent(Alamat))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTambahLayout.setVerticalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NamaSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NoHp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNoHP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Alamat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTambah, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelTambah);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (BtnTambah.getText() == "UBAH") {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
            jLabel2.setText("UBAH DATA SUPPLIER");
            BtnTambah1.setText("SIMPAN");
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Menghapus Data", "Message", JOptionPane.YES_NO_OPTION);
            if (a==0) {
                try {
                    stmt = con.createStatement();
                    String hapus = "DELETE FROM supplier WHERE id_supplier = '" + TextIDSupplier.getText() + "'";
                    stmt.executeUpdate(hapus);  
                    
                    isitabel();
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    BtnTambah.setText("TAMBAH");
                    BtnHapus.setVisible(false);
                    BtnBatal.setVisible(false);
                    
                    bersih();
                    BtnHapus1.setVisible(true);
                    TextIDSupplier.setEditable(true);
                } catch (Exception e) {
                    System.err.println("Error : " + e.getMessage());
                }
            }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        
        BtnTambah.setText("TAMBAH");
        
        jLabel2.setText("TAMBAH DATA SUPPLIER");
        TextIDSupplier.setEditable(true);        
        BtnTambah1.setText("TAMBAH");
        BtnHapus1.setVisible(true);
        
        bersih();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambah1ActionPerformed
        try {
            stmt = con.createStatement();
            if(TextIDSupplier.getText().equals("") || TextNama.getText().equals("") || 
                    TextNoHP.getText().equals("") || TextAlamat.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu");
                return;
            }
            
            //simpan
            if(BtnTambah1.getText() == "TAMBAH") {
                String cek = "SELECT * FROM supplier WHERE id_supplier = '" + TextIDSupplier.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ID Jenis ini Sudah Ada");
                }else{
                    String sql = "INSERT INTO supplier VALUES ('" + TextIDSupplier.getText() + 
                            "','" + TextNama.getText() + 
                            "','" + TextNoHP.getText() + "','" + TextAlamat.getText() + "')";
                    stmt.executeUpdate(sql);
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                    bersih();
                    isitabel();
                    
                    MainPanel.removeAll();
                    MainPanel.repaint();
                    MainPanel.revalidate();
        
                    MainPanel.add(PanelSupplier);
                    MainPanel.repaint();
                    MainPanel.revalidate();
                }
            }else{
                String update = "UPDATE supplier SET nm_supplier = '" + TextNama.getText() +
                        "', nohp_supplier = '" + TextNoHP.getText() +
                        "', alamat_supplier = '" + TextAlamat.getText() +
                        "' WHERE id_supplier = '" + TextIDSupplier.getText() + "'";
                stmt.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
                bersih();
                isitabel();
                
                BtnHapus.setVisible(false);
                BtnBatal.setVisible(false);
                jLabel2.setText("TAMBAH DATA BARANG");
                BtnTambah.setText("TAMBAH");
                
                BtnTambah1.setText("TAMBAH");
                BtnHapus1.setVisible(true);
        
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
        
                MainPanel.add(PanelSupplier);
                MainPanel.repaint();
                MainPanel.revalidate();
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_BtnTambah1ActionPerformed

    private void BtnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapus1ActionPerformed
        bersih();
    }//GEN-LAST:event_BtnHapus1ActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelSupplier);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        bersih();
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void TableSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSupplierMouseClicked
        BtnHapus.setVisible(true);
        BtnBatal.setVisible(true);
        
        BtnTambah.setText("UBAH");
        BtnHapus1.setVisible(false);
        
        TextIDSupplier.setText(TableSupplier.getValueAt(TableSupplier.getSelectedRow(), 0).toString());
        TextNama.setText(TableSupplier.getValueAt(TableSupplier.getSelectedRow(), 1).toString());
        TextNoHP.setText(TableSupplier.getValueAt(TableSupplier.getSelectedRow(), 2).toString());
        TextAlamat.setText(TableSupplier.getValueAt(TableSupplier.getSelectedRow(), 3).toString());
        
        TextIDSupplier.setEditable(false);
    }//GEN-LAST:event_TableSupplierMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamat;
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBatal1;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHapus1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambah1;
    private javax.swing.JLabel IDSupplier;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaSupplier;
    private javax.swing.JLabel NoHp;
    private javax.swing.JPanel PanelSupplier;
    private javax.swing.JPanel PanelTambah;
    private javax.swing.JTable TableSupplier;
    private javax.swing.JTextField TextAlamat;
    private javax.swing.JTextField TextIDSupplier;
    private javax.swing.JTextField TextNama;
    private javax.swing.JTextField TextNoHP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
