/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Master;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmuzaki.a
 */
public class FormMerek extends javax.swing.JPanel {

    /**
     * Creates new form FormMerek
     */
    
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormMerek() {
        initComponents();
        isitabel();
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
    }

    private void bersih() {
        TextIDMerek.setText("");
        TextNama.setText("");
    }
    
    private void isitabel() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM mrk_barang");
            
            DefaultTableModel model = new DefaultTableModel();
                TableMerek.setModel(model);
                model.addColumn("ID Merek");
                model.addColumn("Nama Merek");
                
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_merek"),
                  rs.getString("nm_merek"),
                };
                model.addRow(data);
            }
            
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelMerek = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMerek = new javax.swing.JTable();
        PanelTambah = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnTambah1 = new javax.swing.JButton();
        BtnHapus1 = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        IDMerek = new javax.swing.JLabel();
        TextIDMerek = new javax.swing.JTextField();
        NamaMerek = new javax.swing.JLabel();
        TextNama = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(new java.awt.CardLayout());

        PanelMerek.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA MEREK");

        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TableMerek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Merek", "Nama Merek"
            }
        ));
        TableMerek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMerekMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableMerek);

        javax.swing.GroupLayout PanelMerekLayout = new javax.swing.GroupLayout(PanelMerek);
        PanelMerek.setLayout(PanelMerekLayout);
        PanelMerekLayout.setHorizontalGroup(
            PanelMerekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMerekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMerekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelMerekLayout.createSequentialGroup()
                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelMerekLayout.setVerticalGroup(
            PanelMerekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMerekLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(PanelMerekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(PanelMerek, "card2");

        PanelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TAMBAH DATA MEREK");

        BtnTambah1.setText("TAMBAH");
        BtnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambah1ActionPerformed(evt);
            }
        });

        BtnHapus1.setText("HAPUS");
        BtnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapus1ActionPerformed(evt);
            }
        });

        BtnBatal1.setText("BATAL");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        IDMerek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDMerek.setText("ID Merek");

        TextIDMerek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaMerek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaMerek.setText("Nama Merek");

        TextNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelTambahLayout = new javax.swing.GroupLayout(PanelTambah);
        PanelTambah.setLayout(PanelTambahLayout);
        PanelTambahLayout.setHorizontalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextIDMerek)
                    .addComponent(TextNama, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(PanelTambahLayout.createSequentialGroup()
                        .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTambahLayout.createSequentialGroup()
                                .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(IDMerek)
                            .addComponent(NamaMerek))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTambahLayout.setVerticalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDMerek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaMerek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTambah, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelTambah);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        if (BtnTambah.getText() == "UBAH") {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
            jLabel2.setText("UBAH DATA MEREK");
            BtnTambah1.setText("SIMPAN");
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Menghapus Data", "Message", JOptionPane.YES_NO_OPTION);
            if (a==0) {
                try {
                    stmt = con.createStatement();
                    String hapus = "DELETE FROM mrk_barang WHERE id_merek = '" + TextIDMerek.getText() + "'";
                    stmt.executeUpdate(hapus);  
                    
                    isitabel();
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    BtnTambah.setText("TAMBAH");
                    BtnHapus.setVisible(false);
                    BtnBatal.setVisible(false);
                    
                    bersih();
                    BtnHapus1.setVisible(true);
                    TextIDMerek.setEditable(true);
                } catch (Exception e) {
                    System.err.println("Error : " + e.getMessage());
                }
            }
    }//GEN-LAST:event_BtnHapusActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        
        BtnTambah.setText("TAMBAH");
        
        jLabel2.setText("TAMBAH DATA MEREK");
        TextIDMerek.setEditable(true);        
        BtnTambah1.setText("TAMBAH");
        BtnHapus1.setVisible(true);
        
        bersih();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambah1ActionPerformed
        try {
            stmt = con.createStatement();
            if(TextIDMerek.getText().equals("") || TextNama.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu");
                return;
            }
            
            //simpan
            if(BtnTambah1.getText() == "TAMBAH") {
                String cek = "SELECT * FROM mrk_barang WHERE id_merek = '" + TextIDMerek.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ID Jenis ini Sudah Ada");
                }else{
                    String sql = "INSERT INTO mrk_barang VALUES ('" + TextIDMerek.getText() + 
                            "','" + TextNama.getText() + "')";
                    stmt.executeUpdate(sql);
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                    bersih();
                    isitabel();
                    
                    MainPanel.removeAll();
                    MainPanel.repaint();
                    MainPanel.revalidate();
        
                    MainPanel.add(PanelMerek);
                    MainPanel.repaint();
                    MainPanel.revalidate();
                }
            }else{
                String update = "UPDATE mrk_barang SET nm_merek = '" + TextNama.getText() +
                        "' WHERE id_merek = '" + TextIDMerek.getText() + "'";
                stmt.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
                bersih();
                isitabel();
                
                BtnHapus.setVisible(false);
                BtnBatal.setVisible(false);
                jLabel2.setText("TAMBAH DATA MEREK");
                BtnTambah.setText("TAMBAH");
                
                BtnTambah1.setText("TAMBAH");
                BtnHapus1.setVisible(true);
        
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
        
                MainPanel.add(PanelMerek);
                MainPanel.repaint();
                MainPanel.revalidate();
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_BtnTambah1ActionPerformed

    private void BtnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapus1ActionPerformed
        bersih();
    }//GEN-LAST:event_BtnHapus1ActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelMerek);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        bersih();
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void TableMerekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMerekMouseClicked
        BtnHapus.setVisible(true);
        BtnBatal.setVisible(true);
        
        BtnTambah.setText("UBAH");
        BtnHapus1.setVisible(false);
        
        TextIDMerek.setText(TableMerek.getValueAt(TableMerek.getSelectedRow(), 0).toString());
        TextNama.setText(TableMerek.getValueAt(TableMerek.getSelectedRow(), 1).toString());
        
        TextIDMerek.setEditable(false);
    }//GEN-LAST:event_TableMerekMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBatal1;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHapus1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambah1;
    private javax.swing.JLabel IDMerek;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaMerek;
    private javax.swing.JPanel PanelMerek;
    private javax.swing.JPanel PanelTambah;
    private javax.swing.JTable TableMerek;
    private javax.swing.JTextField TextIDMerek;
    private javax.swing.JTextField TextNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
