/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Master;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author mmuzaki.a
 */
public class FormBarang extends javax.swing.JPanel {

    /**
     * Creates new form FormBarang
     */
    public Statement stmt;
    public ResultSet rs;
    public PreparedStatement pstmt;
    Connection con = Koneksi.KoneksiD.BukaKoneksi();
    
    public FormBarang() {
        initComponents();
        isitabel();
        cbb_jenis();
        cbb_merek();
        cbb_supplier();
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
    }

    private void bersih() {
        TextIDBarang.setText("");
        TextNama.setText("");
        ComboBoxJenis.setSelectedItem("Pilih Jenis Barang");
        ComboBoxMerek.setSelectedItem("Pilih Merek Barang");
        ComboBoxSupplier.setSelectedItem("Pilih Nama Supplier");
        TextHarga.setText("");
        TextStok.setText("");
    }
    
    private void isitabel() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM barang");
            
            DefaultTableModel model = new DefaultTableModel();
                TableBrng.setModel(model);
                model.addColumn("ID Barang");
                model.addColumn("Nama Barang");
                model.addColumn("Jenis Barang");
                model.addColumn("Merek Barang");
                model.addColumn("Nama Supplier");
                model.addColumn("Harga Barang");
                model.addColumn("Stok Barang");
            
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while (rs.next()) {
                Object[] data = {
                  rs.getString("id_barang"),
                  rs.getString("nm_barang"),
                  rs.getString("nm_jenis"),
                  rs.getString("nm_merek"),
                  rs.getString("nm_supplier"),
                  rs.getString("hrg_barang"),
                  rs.getString("stok_barang")
                };
                model.addRow(data);
                //TableBrng.setModel(model);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
    }
    
    private void cbb_jenis() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM jns_barang");
            
            while (rs.next()) {
                String jns = rs.getString("nm_jenis");
                ComboBoxJenis.addItem(jns);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
        
    }
    
    private void cbb_merek() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM mrk_barang");
            
            while (rs.next()) {
                String mrk = rs.getString("nm_merek");
                ComboBoxMerek.addItem(mrk);
                              
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
                       
    }
       
    private void cbb_supplier() {
        try {
            stmt = con.createStatement();
            rs = stmt.executeQuery("SELECT * FROM supplier");
            
            while (rs.next()) {
                String sup = rs.getString("nm_supplier");
                ComboBoxSupplier.addItem(sup);
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
          
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        PanelData = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnTambah = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        BtnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableBrng = new javax.swing.JTable();
        PanelTambah = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BtnTambah1 = new javax.swing.JButton();
        BtnBatal1 = new javax.swing.JButton();
        BtnHapus1 = new javax.swing.JButton();
        IDBarang = new javax.swing.JLabel();
        TextIDBarang = new javax.swing.JTextField();
        NamaBarang = new javax.swing.JLabel();
        TextNama = new javax.swing.JTextField();
        IDJenis = new javax.swing.JLabel();
        ComboBoxJenis = new javax.swing.JComboBox<>();
        IDMerek = new javax.swing.JLabel();
        ComboBoxMerek = new javax.swing.JComboBox<>();
        IDSupplier = new javax.swing.JLabel();
        ComboBoxSupplier = new javax.swing.JComboBox<>();
        HargaBarang = new javax.swing.JLabel();
        TextHarga = new javax.swing.JTextField();
        StokBarang = new javax.swing.JLabel();
        TextStok = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setLayout(new java.awt.CardLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        PanelData.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA BARANG");

        BtnTambah.setText("TAMBAH");
        BtnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambahActionPerformed(evt);
            }
        });

        BtnBatal.setText("BATAL");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        BtnHapus.setText("HAPUS");
        BtnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapusActionPerformed(evt);
            }
        });

        TableBrng.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Barang", "Nama Barang", "Jenis Barang", "Merek Barang", "Nama Supplier", "Harga Barang", "Stok Barang"
            }
        ));
        TableBrng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBrngMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableBrng);

        javax.swing.GroupLayout PanelDataLayout = new javax.swing.GroupLayout(PanelData);
        PanelData.setLayout(PanelDataLayout);
        PanelDataLayout.setHorizontalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(PanelDataLayout.createSequentialGroup()
                        .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelDataLayout.setVerticalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        MainPanel.add(PanelData, "card2");

        PanelTambah.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TAMBAH DATA BARANG");

        BtnTambah1.setText("TAMBAH");
        BtnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTambah1ActionPerformed(evt);
            }
        });

        BtnBatal1.setText("BATAL");
        BtnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatal1ActionPerformed(evt);
            }
        });

        BtnHapus1.setText("HAPUS");
        BtnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHapus1ActionPerformed(evt);
            }
        });

        IDBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDBarang.setText("ID Barang");

        TextIDBarang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        NamaBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NamaBarang.setText("Nama Barang");

        TextNama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        IDJenis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDJenis.setText("ID Jenis");

        ComboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Barang" }));

        IDMerek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDMerek.setText("ID Merek");

        ComboBoxMerek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Merek Barang" }));

        IDSupplier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDSupplier.setText("ID Supplier");

        ComboBoxSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Supplier" }));

        HargaBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HargaBarang.setText("Harga Barang");

        TextHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        StokBarang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StokBarang.setText("Stok Barang");

        TextStok.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout PanelTambahLayout = new javax.swing.GroupLayout(PanelTambah);
        PanelTambah.setLayout(PanelTambahLayout);
        PanelTambahLayout.setHorizontalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextIDBarang)
                    .addComponent(TextNama, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(ComboBoxJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxMerek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBoxSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addComponent(TextStok, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(PanelTambahLayout.createSequentialGroup()
                        .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDBarang)
                            .addComponent(NamaBarang)
                            .addComponent(IDJenis)
                            .addComponent(IDMerek)
                            .addComponent(IDSupplier)
                            .addComponent(HargaBarang)
                            .addComponent(StokBarang)
                            .addGroup(PanelTambahLayout.createSequentialGroup()
                                .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelTambahLayout.setVerticalGroup(
            PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTambahLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(PanelTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnTambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBatal1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NamaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextNama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDJenis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDMerek)
                .addGap(2, 2, 2)
                .addComponent(ComboBoxMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IDSupplier)
                .addGap(2, 2, 2)
                .addComponent(ComboBoxSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HargaBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StokBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextStok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        MainPanel.add(PanelTambah, "card2");

        add(MainPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambah1ActionPerformed
        try {
            stmt = con.createStatement();
            if(TextIDBarang.getText().equals("") || TextNama.getText().equals("") || 
                    ComboBoxJenis.getSelectedItem().equals("Pilih Jenis Barang") || 
                    ComboBoxMerek.getSelectedItem().equals("Pilih Merek Barang") || 
                    ComboBoxSupplier.getSelectedItem().equals("Pilih Nama Supplier") || 
                    TextHarga.getText().equals("") || TextStok.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Isi semua data terlebih dahulu");
                return;
            }
            
            //simpan
            if (BtnTambah1.getText() == "TAMBAH") {
                String cek = "SELECT * FROM barang WHERE id_barang = '" + TextIDBarang.getText() + "'";
                rs = stmt.executeQuery(cek);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "ID Barang ini Sudah Ada");
                }else{
                    String sql = "INSERT INTO barang VALUES ('" + TextIDBarang.getText() + 
                        "','" + TextNama.getText() + "','" + ComboBoxJenis.getSelectedItem() + 
                        "','" + ComboBoxMerek.getSelectedItem() + "','" + ComboBoxSupplier.getSelectedItem() + 
                        "','" + TextHarga.getText() + "','" + TextStok.getText() + "')";
                    stmt.executeUpdate(sql);                
                
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
                    bersih();
                    isitabel();
                    
                    MainPanel.removeAll();
                    MainPanel.repaint();
                    MainPanel.revalidate();
        
                    MainPanel.add(PanelData);
                    MainPanel.repaint();
                    MainPanel.revalidate();
                }
            }else{
                String update = "UPDATE barang SET nm_barang = '" + TextNama.getText() +
                    "', nm_jenis = '" + ComboBoxJenis.getSelectedItem() +
                    "', nm_merek = '" + ComboBoxMerek.getSelectedItem() +
                    "', nm_supplier = '" + ComboBoxSupplier.getSelectedItem() +
                    "', hrg_barang = '" + TextHarga.getText() +
                    "', stok_barang = '" + TextStok.getText() +
                    "' WHERE id_barang = '" + TextIDBarang.getText() + "'";
                stmt.executeUpdate(update);
                
                JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
                bersih();
                isitabel();
                
                BtnHapus.setVisible(false);
                BtnBatal.setVisible(false);
                jLabel3.setText("TAMBAH DATA BARANG");
                BtnTambah.setText("TAMBAH");
                
                BtnTambah1.setText("TAMBAH");
                BtnHapus1.setVisible(true);
        
                MainPanel.removeAll();
                MainPanel.repaint();
                MainPanel.revalidate();
        
                MainPanel.add(PanelData);
                MainPanel.repaint();
                MainPanel.revalidate();
            }
        } catch (Exception e) {
            System.err.println("Error : " + e.getMessage());
        }
  
    }//GEN-LAST:event_BtnTambah1ActionPerformed

    private void BtnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTambahActionPerformed
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
        if (BtnTambah.getText() == "UBAH") {
            MainPanel.removeAll();
            MainPanel.repaint();
            MainPanel.revalidate();
        
            MainPanel.add(PanelTambah);
            MainPanel.repaint();
            MainPanel.revalidate();
            
            jLabel3.setText("UBAH DATA BARANG");
            BtnTambah1.setText("SIMPAN");
            
        }
    }//GEN-LAST:event_BtnTambahActionPerformed

    private void BtnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatal1ActionPerformed
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
        
        MainPanel.add(PanelData);
        MainPanel.repaint();
        MainPanel.revalidate();
        
        bersih();
    }//GEN-LAST:event_BtnBatal1ActionPerformed

    private void TableBrngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBrngMouseClicked
        BtnTambah.setText("UBAH");
        BtnHapus.setVisible(true);
        BtnBatal.setVisible(true);
        BtnHapus1.setVisible(false);
        
            TextIDBarang.setText(TableBrng.getValueAt(TableBrng.getSelectedRow(), 0).toString());
            TextNama.setText(TableBrng.getValueAt(TableBrng.getSelectedRow(), 1).toString());
            ComboBoxJenis.setSelectedItem(TableBrng.getValueAt(TableBrng.getSelectedRow(), 2).toString());
            ComboBoxMerek.setSelectedItem(TableBrng.getValueAt(TableBrng.getSelectedRow(), 3).toString());
            ComboBoxSupplier.setSelectedItem(TableBrng.getValueAt(TableBrng.getSelectedRow(), 4).toString());
            TextHarga.setText(TableBrng.getValueAt(TableBrng.getSelectedRow(), 5).toString());
            TextStok.setText(TableBrng.getValueAt(TableBrng.getSelectedRow(), 6).toString());
            
            TextIDBarang.setEditable(false);
    }//GEN-LAST:event_TableBrngMouseClicked

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        BtnTambah.setText("TAMBAH");
        BtnHapus.setVisible(false);
        BtnBatal.setVisible(false);
        BtnHapus1.setVisible(true);
        jLabel3.setText("TAMBAH DATA BARANG");
        TextIDBarang.setEditable(true);
        
        bersih();
        BtnTambah1.setText("TAMBAH");
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void BtnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapus1ActionPerformed
        bersih();
    }//GEN-LAST:event_BtnHapus1ActionPerformed

    private void BtnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHapusActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"Apakah Yakin Ingin Menghapus Data", "Message", JOptionPane.YES_NO_OPTION);
            if (a==0) {
                try {
                    stmt = con.createStatement();
                    String hapus = "DELETE FROM barang WHERE id_barang = '" + TextIDBarang.getText() + "'";
                    stmt.executeUpdate(hapus);  
                    
                    isitabel();
                    
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Hapus");
                    BtnTambah.setText("TAMBAH");
                    BtnHapus.setVisible(false);
                    BtnBatal.setVisible(false);                   
                    
                    bersih();
                    BtnHapus1.setVisible(true);
                    TextIDBarang.setEditable(true);
                } catch (Exception e) {
                    System.err.println("Error : " + e.getMessage());
                }
                
            }
    }//GEN-LAST:event_BtnHapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBatal1;
    private javax.swing.JButton BtnHapus;
    private javax.swing.JButton BtnHapus1;
    private javax.swing.JButton BtnTambah;
    private javax.swing.JButton BtnTambah1;
    private javax.swing.JComboBox<String> ComboBoxJenis;
    private javax.swing.JComboBox<String> ComboBoxMerek;
    private javax.swing.JComboBox<String> ComboBoxSupplier;
    private javax.swing.JLabel HargaBarang;
    private javax.swing.JLabel IDBarang;
    private javax.swing.JLabel IDJenis;
    private javax.swing.JLabel IDMerek;
    private javax.swing.JLabel IDSupplier;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel NamaBarang;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelTambah;
    private javax.swing.JLabel StokBarang;
    private javax.swing.JTable TableBrng;
    private javax.swing.JTextField TextHarga;
    private javax.swing.JTextField TextIDBarang;
    private javax.swing.JTextField TextNama;
    private javax.swing.JTextField TextStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
